### ISSUE TITLE
[Feature Request] Limited Trading

### ISSUE THREAD

**Issue by quietlynn** [NyaaCat/NyaaPlayerCoser#1]
This is a feature request to put limits to NPC trading. The motivation is to allow reasonable trading without using some hard-to-obtain items, while still preventing potential abuse. Many games, especially MMORPG games with markets, utilizes similar ideas to make the economy more controllable.

Limits can include:

* Limited stock: Each trade can have a limited amount of stock available, which can be automatically replenished in time (e.g. each new item arrive every Y hours). The limit is shared among all players.
* Per-player transaction limits: Each player can only perform a certain trade up to X times (over lifetime / in Y game hours / in Y PTT hours).

Use cases:

* Starter kits / promotional items: Can be limited to one trade per player. This replaces the need of `[kit]` signs.
* Key items / plot-related items / event items: Can be limited to one trade per player. Especially, for recurring events (e.g. monthly city tours), time-based per-player limits can be used instead of `/ptt ac`.
* Informational items (e.g. news, tutorials) can reach more players in this way. Each player should only need one of those items (or a second for their friend).
* Non-profit or charity sales.
* Trades intended for vanilla players: Can be limited to X trades per player to prevent pointless mob/corp farming. In this way, each player is encouraged to gather on his/her own instead of purchasing batch-produced items from one or two players.

Finally, the use of limits encourage admins / players to set up and experiment easier trades (maybe at lower stock first), while still providing a "safety net" in case a trade is subject to abuse or leads to excessive grinding. One does not need to search him/her brain to come up with some hard-to-obtain items just for the sake of preventing abuse.

**Comment by quietlynn** [comment]
Purposed configuration file format should allow multiple rule groups. Each rule group is named and each trade (or NPC?) can be associated with one group. Example (thanks to @phoenixlzx ):

```yaml
limit-group:
  g1:
    stock-limit: 3 # The store can hold max of 3 items at any time.
    replenish-interval: 3600  # Each item arrives in 3600 seconds, if not already full.
    per-player-transactions: 3  # Each player can conduct at most 3 trades.
    per-player-transaction-interval: 3600 # A player can conduct one more trade every 3600 seconds.
  g2:
    stock-limit: 3
    replenish-interval: -1  # New items won't arrive. It's limited availability.
    per-player-transactions: 10  # Each player can conduct at most 10 trades lifetime.
    per-player-transaction-interval: -1 # After player has exhausted 10 trades, there is no more.
  g3:
    stock-limit: -1  # No limit, trade as much as you want.
    replenish-interval: 123  # Ignored if stock limit is -1.
    per-player-transactions: -1  # No limit, trade as much as you want.
    per-player-transaction-interval: 456 # Ignored if transaction limit is -1.
```

`g1` and `g2` are two different groups. Inside each group, the `replenish-interval` and `per-player-transactions` are BOTH in effect, meaning that BOTH stock and per-player limits are enforced. For example, if a trade is tagged `g1`, then players cannot make the trade if the item is out of stock. Likewise, if a player has used up his/her own quota, trading is disabled even if there is still stock available. Again, stock / quota is applied individually to each trade/NPC. Two trade/NPCs do not share any stock / quota even if they are tagged using the same group.

TBD: Shall we enforce limits on the NPC level or the trade level? Limiting to NPC can support some interesting use cases such as forcing the player to make a choice, or to enforce a "bigger limit" if one NPC offers multiple recipes for a single item (e.g. fuel). However, shop creators are then forced to create separate NPCs if they intend to use separate limits (For example, `sand -> fuel -> fuel ingot -> fuel coupon` may require three different NPCs to be fully scalable. Otherwise, trading in fuel could exhaust fuel coupons as well, leading to surprising results.) Having related transactions grouped into one single NPC also looks nicer (taking the fuel example again).
